### ISSUE TITLE
Consider renaming to Corvus.CosmosDb.Extensions

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Extensions.CosmosDb#46]
The current naming implies the `Corvus.Extensions` is the area of functionality, and `CosmosDb` the area of specialization. @idg10 and @jamesbroome think that it makes more sense the other way around. In any case, we're not currently consistent, because `Corvus.SpecFlow.Extensions` is a thing.

**Comment by mwadams** [comment]
I think we should definitely do this.

In addition, we should review the naming convention decisions we made when struggling with the inside-outside-upside-down storage.blah.foo.bar.storage namespaces we had, and make sure we clearly document the conventions for various circumstances (somewhere - is there something organization-level we can do?)

**Comment by idg10** [comment]
We don't currently have a Corvus..Net org-wide place for ADRs. Some suggested names:

* corvus-dotnet/Corvus.Net
* corvus-dotnet/corvus-dotnet
* corvus-dotnet/conventions
* corvus-dotnet/design
* corvus-dotnet/architecture
* corvus-dotnet/adrs

**Comment by HowardvanRooijen** [comment]
Isn't `corvus-dotnet/corvus-dotnet` a special case repo name that's used for org profiles?

**Comment by idg10** [comment]
Not sure, but having tried to find out I've discovered that this repo name is apparently special to GitHub pages, which may matter once we work out how to aggregate DocFX content across the various projects. So I think that rules that one out.
